version: "3.8"

services:
  webapp:
    build: ./
    image: webapp
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: always
    ports:
      - 8000:8000
    env_file:
      - .env-docker
    volumes:
      - "./:/app"
